name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        enable-stack: true
        stack-version: 'latest'
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y lld
        sudo apt-get install -y llvm
        
    - name: Configure
      run: python configure.py
    - name: Build runtime
      run: cd runtime && make && cd ../
    - name: Build compiler
      run: stack build
    - name: Run tests
      run: stack test
